# Generated by Django 4.1.2 on 2023-01-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=128)),
                ("author", models.CharField(max_length=64)),
            ],
        ),
    ]
